title: Jiyang Tang
description: >-
  Jiyang Tang's personal website
baseurl: ""
url: "https://tjysdsg.github.io"
timezone: US/Pacific
markdown: kramdown
locale: "en-US"
repository: tjysdsg/tjysdsg.github.io

# default front matters
defaults:
  - scope:
      path: ""
      type: posts
    values:
      # settings about minimal-mistakes-jekyll
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: false
      show_date: true
      excerpt_separator: "<!--more-->"

      # markdown engine
      usemathjax: true


################ minimal-mistakes-jekyll ################
# author
author:
  name: "Jiyang Tang"
  url: "https://tjysdsg.github.io"
  avatar: "/assets/images/me.jpg"
  bio: "SWE@Intel"
  location: "Hillsboro, OR, United States"
  email: jiyang.mark.tang@gmail.com
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/tjy"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tjysdsg"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JiyangTang"


################ jekyll-seo-tag ################
logo: /assets/images/apple-touch-icon.png
social:
  name: Jiyang Tang
  links:
    - https://github.com/tjysdsg
    - https://www.linkedin.com/in/tjy/
    - https://twitter.com/JiyangTang

################ jekyll scholar ################
scholar:
  style: ieee
  bibliography: references.bib

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll/scholar

# Not using this because it puts the tag in the body but we want it to be in the header so that Google search
# console can discover it

# Google Analytics
# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "G-WYHC5BDEPZ"
#     anonymize_ip: false