title: Jiyang Tang
email: tjy1018543509@google.com
description: >-
  Jiyang Tang's personal website
tagline: Jiyang Tang | 唐际洋
baseurl: ""
url: "https://tjysdsg.github.io"
timezone: US/Eastern
markdown: kramdown

# default front matters
defaults:
  - scope:
      path: ""
      type: posts
    values:
      # settings about minimal-mistakes-jekyll
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: false
      show_date: true
      excerpt_separator: "<!--more-->"

      # markdown engine
      usemathjax: true


################ minimal-mistakes-jekyll ################
# author
author:
  name: "Jiyang Tang"
  url: "https://tjysdsg.github.io"
  avatar: "/assets/images/me.jpg"
  bio: " "
  location: "Pittsburgh, PA, United States"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/tjy"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tjysdsg"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/tjysxsg"


################ jekyll-seo-tag ################
logo: /assets/images/me.jpg
social:
  name: Jiyang Tang
  links:
    - https://github.com/tjysdsg
    - https://www.linkedin.com/in/tjy/
    - https://twitter.com/tjysxsg

################ jekyll scholar ################
scholar:
  style: ieee
  bibliography: references.bib

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll/scholar

# Google Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-WYHC5BDEPZ"
    anonymize_ip: false